apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-stream-ingestion-deployment
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: client-stream-ingestion
  template:
    metadata:
      labels:
        app: client-stream-ingestion
    spec:
      containers:
      - name: client-stream-ingestion-cron
        image: client-stream-ingestion:latest
        imagePullPolicy: Never
        env:
          - name: SOURCE_PATH
            value: "/data"
          - name: CLIENT_ID
            value: "1"
        volumeMounts:
          - name: data-volume
            mountPath: /data
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
      volumes:
      - name: data-volume
        hostPath:
          path: /data/client-staging-input-directory
